version: '3.9'

services:
# DATABASES
  db-grade:
    container_name: db-grade
    image: postgres
    ports:
      - 4006:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: db_grade
      PGPASSWORD: 1234
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-U",
          "root",
          "-d",
          "db_grade"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"
# MICROSERVICES
  ms-campus-kid-grades:
    container_name: ms-campus-kid-grades
    build: ./ms-campus-kid-grades
    depends_on:
      db-grade:
        condition: service_healthy
    links:
      - db-grade
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - SECRET_KEY=1234P
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=db_grade
      - DB_PORT=4006
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ms-campus-kid-schedule:
    container_name: ms-campus-kid-schedule
    build: ./ms-campus-kid-schedule
    depends_on:
      db-grade:
        condition: service_healthy
    links:
      - db-grade
    ports:
      - 4003:4003
    environment:
      - PORT=4003
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=db_grade
      - DB_PORT=4006
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
# otro ms
  appweb-campus-kid:
    container_name: appweb-campus-kid
    build: ./appweb-campus-kid
    links:
      - ag-campus-kid
    ports:
      - 5000:3000
    environment:
      - PORT=5000
   
# API_GATEWAY
  ag-campus-kid:
    container_name: ag-campus-kid
    build: ./ag-campus-kid
    ports:
      - 4011:4011
    environment:
      - PORT=4011
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"