// <auto-generated />
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(SubjectsContext))]
    [Migration("20221015014915_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataBase.Career", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("facultyId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.HasIndex("facultyId");

                    b.ToTable("Career", (string)null);
                });

            modelBuilder.Entity("DataBase.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("facultyId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("facultyId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("siteId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("siteId");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("DataBase.Site", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("id");

                    b.HasIndex("name", "code")
                        .IsUnique();

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("DataBase.Career", b =>
                {
                    b.HasOne("DataBase.Faculty", "faculty")
                        .WithMany("careers")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("faculty");
                });

            modelBuilder.Entity("DataBase.Course", b =>
                {
                    b.HasOne("DataBase.Faculty", "faculty")
                        .WithMany("courses")
                        .HasForeignKey("facultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("faculty");
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.HasOne("DataBase.Site", "site")
                        .WithMany("faculties")
                        .HasForeignKey("siteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("site");
                });

            modelBuilder.Entity("DataBase.Faculty", b =>
                {
                    b.Navigation("careers");

                    b.Navigation("courses");
                });

            modelBuilder.Entity("DataBase.Site", b =>
                {
                    b.Navigation("faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
